version: '3.8'

services:
  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: valkey_metrics
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge

volumes:
  valkey_data: